### ISSUE TITLE
RequestParams throwing MISSING_SERVLET_REQUEST_PARAMETER instead of VALIDATION_FAILED

### ISSUE THREAD

**Issue by bwgjoseph** [wimdeblauwe/error-handling-spring-boot-starter#46]
Hi,

It wasn't very clear in the documentation whether `@RequestParams` would throw `VALIDATION_FAILED` code but I assume so, especially with the example in #20 

I have a small demo

```
// dependencies
implementation 'org.springframework.boot:spring-boot-starter-web'
implementation 'org.hibernate:hibernate-validator:7.0.4.Final'
implementation 'io.github.wimdeblauwe:error-handling-spring-boot-starter:2.1.0'
```

```java
@Validated
@RestController
class ErrorController {
	@GetMapping("/demo")
	public ResponseEntity<Integer> demo(@RequestParam @NotEmpty String test) {
		return ResponseEntity.ok(1);
	}
}
```

And it throws

![image](https://user-images.githubusercontent.com/37484538/162562675-180482ba-c605-4846-9bb4-e7e31beeb73a.png)

Is this the intended behavior, or did I use it wrongly?

Thanks!

**Comment by wimdeblauwe** [comment]
A fix for this will be added in the upcoming version 3.0.0 along with support for the other "sibling" exceptions:

* MissingMatrixVariableException
* MissingRequestHeaderException
* MissingServletRequestParameterException
* MissingPathVariableException
* MissingRequestCookieException

Since 3.0.0 will also support Spring WebFlux, there will also be support for the ServerWebInputException and ServerErrorException exceptions that are using in a reactive application for the same problems.

**Comment by wimdeblauwe** [comment]
Version 3.0.0 is now released.
